### ISSUE TITLE
Creds from AWS IoT Credentials Provider failure

### ISSUE THREAD

**Issue by philcali** [philcali/pits-device#5]
```
Jun 10 07:59:09 raspberrypi pinthesky[27632]: 2022-06-10 07:59:09,788 pinthesky.combiner [INFO] Finish concatinating to /usr/share/pinthesky/motion_videos/1654862316.motion.h264
Jun 10 07:59:11 raspberrypi pinthesky[27632]: Exception in thread Thread-1:
Jun 10 07:59:11 raspberrypi pinthesky[27632]: Traceback (most recent call last):
Jun 10 07:59:11 raspberrypi pinthesky[27632]:   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
Jun 10 07:59:11 raspberrypi pinthesky[27632]:     self.run()
Jun 10 07:59:11 raspberrypi pinthesky[27632]:   File "/usr/local/lib/python3.9/dist-packages/pinthesky/events.py", line 56, in run
Jun 10 07:59:11 raspberrypi pinthesky[27632]:     handler(message)
Jun 10 07:59:11 raspberrypi pinthesky[27632]:   File "/usr/local/lib/python3.9/dist-packages/pinthesky/upload.py", line 29, in on_combine_end
Jun 10 07:59:11 raspberrypi pinthesky[27632]:     creds['accessKeyId'],
Jun 10 07:59:11 raspberrypi pinthesky[27632]: KeyError: 'accessKeyId'

```

Looks like a missing key or wrong payload.

**Comment by philcali** [comment]
Tested in a REPL ... payload is wrapped in a `credentials` document:

```
>>> session.login()
{'credentials': {'accessKeyId': '[REDACTED]', 'secretAccessKey': '[REDACTED]', 'sessionToken': '[REDACTED]', 'expiration': '2022-06-10T23:51:15Z'}}
```
